       # screen_width = self.window.winfo_screenwidth()
        # screen_height = self.window.winfo_screenheight()
        # x = (screen_width // 2) - (window_width // 2)
        # y = (screen_height // 2) - (window_height // 2)
        # self.window.geometry(f'{window_width}x{window_height}+{x}+{y}')